### ISSUE TITLE
Native HomeKit instead?

### ISSUE THREAD

**Issue by thenewwazoo** [ratgdo/homebridge-ratgdo#1]
I've undertaken writing a HomeKit-native firmware for the ratgdo, and noticed this proto-repository, which has a name that suggests a Homebridge plugin. I'm sorry to be "That Guy", but instead of writing a Homebridge plugin, I'd like to suggest writing a HomeKit-native firmware instead. It requires answering all the same questions about services and characteristics that you must with Homebridge (service Garage Door Opener, characteristics Current Door State, Target Door State, and so on), so the development is very similar and quite straightforward. In fact, almost all of my time right now is being spent on understanding the wireline data model and supported message types, and most of the HomeKit-specific stuff can be cribbed [from examples](https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/garage).

If you'd like some code to bootstrap the process, I'd be happy to provide it. :)

**Comment by PaulWieland** [comment]
Hi Brandon, would you mind becoming a co-author and putting the repo under github.com/ratgdo? I can send you an invite...

**Comment by thenewwazoo** [comment]
Of course!

**Comment by PaulWieland** [comment]
I just setup the repo and added you as a maintainer.
